name: Debug Cache Only
on:
  workflow_dispatch:  # Kan kjøres manuelt

jobs:
  debug-cache:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache vcpkg build artifacts
        uses: actions/cache@v3
        with:
          path: |
            vcpkg\installed
            vcpkg\buildtrees
            vcpkg\downloads
            vcpkg\packages
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-
      
      - name: Check cache contents
        shell: pwsh
        run: |
          Write-Host "=== CACHE DEBUG ==="
          if (Test-Path "vcpkg") {
            Get-ChildItem "vcpkg" -Recurse -Directory | Select-Object FullName
          } else {
            Write-Host "No vcpkg directory found"
          }
          Write-Host "=== END DEBUG ==="
