name: Build (CMake + vcpkg on Windows)

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache vcpkg build artifacts
        uses: actions/cache@v3
        with:
          path: |
            vcpkg/installed
            vcpkg/buildtrees
            vcpkg/downloads
            vcpkg/packages
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-
            
      - name: Install CMake
        uses: lukka/get-cmake@latest
        
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3
        
      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          
      - name: Install dependencies via vcpkg (manifest mode)
        run: |
          .\vcpkg\vcpkg.exe install --triplet x64-windows
          
      - name: Configure CMake
        run: |
          cmake -B build -S . -G "Ninja" `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_TESTS=ON
            
      - name: Build
        run: |
          cmake --build build --config Release
          
      - name: Run Tests
        run: |
          ctest --test-dir build --output-on-failure --verbose
          
      - name: Run Tests (Alternative - Direct Executable)
        if: failure()
        run: |
          .\build\bin\netcode_tests.exe
          
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            build/Testing/
            build/bin/