name: Build (CMake + vcpkg)

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            vcpkg_installed
            ~/.cache/vcpkg
            ~/.vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
      
      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure (CMake Presets)
        run: cmake --preset x64-debug
        env:
          VCPKG_FEATURE_FLAGS: manifests

      - name: Build (CMake Presets)
        run: cmake --build --preset x64-debug

      - name: Run tests (if you have tests)
        run: ctest --preset x64-debug || true
        if: always()
