name: Build (CMake + vcpkg on Windows & macOS)
on:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
      
      - name: Cache vcpkg build artifacts
        uses: actions/cache@v3
        with:
          path: |
            vcpkg\buildtrees
            vcpkg\downloads
            vcpkg\packages
            vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-
      
      - name: Install Doxygen
        shell: pwsh
        run: |
          choco install doxygen.install -y
      
      - name: Configure and build  
        shell: pwsh
        run: |
          cmake -B build -S . -G "Visual Studio 17 2022" -A x64 \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET=x64-windows
          cmake --build build --config Release
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-windows
          path: build/
          retention-days: 1
  
  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output-windows
          path: build/
      
      - name: Run tests
        shell: pwsh
        run: |
          ctest --test-dir build --output-on-failure --build-config Release

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Cache vcpkg build artifacts
        uses: actions/cache@v3
        with:
          path: |
            vcpkg/buildtrees
            vcpkg/downloads
            vcpkg/packages
            vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install Doxygen
        run: brew install doxygen

      - name: Configure and build  
        run: |
          cmake -B build -S . \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
          cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos
          path: build/
          retention-days: 1

  test-macos:
    runs-on: macos-latest
    needs: build-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos
          path: build/

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure --build-config Release
