name: CI (build + test)

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        run_tests: ["OFF", "ON"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Cache vcpkg build artifacts
        uses: actions/cache@v3
        with:
          path: |
            vcpkg\installed
            vcpkg\buildtrees
            vcpkg\downloads
            vcpkg\packages
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install dependencies via vcpkg
        shell: pwsh
        run: |
          .\vcpkg\vcpkg.exe install --triplet x64-windows

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure
        shell: pwsh
        run: |
          cmake -B build -S . -G Ninja `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_TESTS=${{ matrix.run_tests }}

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        if: matrix.run_tests == 'ON'
        run: ctest --test-dir build --output-on-failure
