name: Debug Cache Structure
on: [push, pull_request]

jobs:
  debug:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
      
      - name: Cache vcpkg build artifacts
        uses: actions/cache@v3
        with:
          path: |
            vcpkg\installed
            vcpkg\buildtrees
            vcpkg\downloads
            vcpkg\packages
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-
      
      - name: DEBUG - Show cache structure
        shell: pwsh
        run: |
          Write-Host "=== CACHE STRUCTURE DEBUG ==="
          Write-Host "Current directory contents:"
          Get-ChildItem . -Name
          Write-Host ""
          
          if (Test-Path "vcpkg") {
            Write-Host "vcpkg directory exists"
            Write-Host "vcpkg contents:"
            Get-ChildItem "vcpkg" -Name
            Write-Host ""
            
            if (Test-Path "vcpkg\installed") {
              Write-Host "vcpkg\installed exists"
              Write-Host "vcpkg\installed contents:"
              Get-ChildItem "vcpkg\installed" -Name
              Write-Host ""
              
              if (Test-Path "vcpkg\installed\x64-windows") {
                Write-Host "vcpkg\installed\x64-windows exists"
                Write-Host "vcpkg\installed\x64-windows contents:"
                Get-ChildItem "vcpkg\installed\x64-windows" -Name -ErrorAction SilentlyContinue
                Write-Host ""
                
                if (Test-Path "vcpkg\installed\x64-windows\lib") {
                  Write-Host "✅ LIB DIRECTORY EXISTS!"
                  Write-Host "lib contents:"
                  Get-ChildItem "vcpkg\installed\x64-windows\lib" -Name -ErrorAction SilentlyContinue
                } else {
                  Write-Host "❌ lib directory does not exist"
                }
                
                if (Test-Path "vcpkg\installed\x64-windows\include") {
                  Write-Host "✅ INCLUDE DIRECTORY EXISTS!"
                } else {
                  Write-Host "❌ include directory does not exist"
                }
              } else {
                Write-Host "❌ vcpkg\installed\x64-windows does not exist"
              }
            } else {
              Write-Host "❌ vcpkg\installed does not exist"
            }
          } else {
            Write-Host "❌ vcpkg directory does not exist"
          }
          Write-Host "=== END DEBUG ==="
      
      - name: Install dependencies via vcpkg (manifest mode)
        shell: pwsh
        run: |
          .\vcpkg\vcpkg.exe install --triplet x64-windows