name: C++ CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache vcpkg installed
        uses: actions/cache@v3
        with:
          path: C:/vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: true
          cleanAfterBuild: true
          useVcpkgCache: true

      - name: Build Solution (parallel)
        run: msbuild netcode-demo.sln /m /p:CL_MPCount=8 /p:Configuration=Debug /p:VcpkgEnableManifest=true
        shell: cmd
