name: C++ CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: true
          cleanAfterBuild: true
          useVcpkgCache: false 

      - name: Build Solution
        run: msbuild netcode-demo.sln /p:Configuration=Debug /p:VcpkgEnableManifest=true
        shell: cmd
